export enum PortAction { 
    INIT = "INIT",
    SWIPED_PERSON_ACTION_START = "SWIPED-PERSON-ACTION-START",
    SWIPED_PERSON_ACTION_PROCESS = "SWIPED-PERSON-ACTION-PROCESS", 
    SWIPED_PERSON_ACTION_END = "SWIPED-PERSON-ACTION-END",
    SUBMIT_ACTION = "SUBMIT-ACTION",
    GET_NETWORK_LOGS = "GET-NETWORK-LOGS",
    FILENAME = "FILENAME",
    KEEP_ALIVE = "KEEP-ALIVE",
}